### ISSUE TITLE
For discussion

### ISSUE THREAD

**Issue by brandonsheppard** [demiscient/demitheme#7]
What does [this](https://github.com/demiscient/demitheme/blob/master/src/css/app.less#L2597-L2603) do?

**Comment by demiscient** [comment]
I don't... quite know..

**Comment by demiscient** [comment]
Oh wait, yes I do, I was trying to add some hover effects for when you're leaving reviews and selecting stars (always bothered me that there is no hover effect for them, so user is left not entirely sure you can click on the stars) and I was experimenting and it didn't work because I realised it was completely out of my depth.
